### ISSUE TITLE
Panic on MSP430FR2433 target

### ISSUE THREAD

**Issue by jaycle** [pftbest/msp430_svd#1]
While trying to generate svd files for the MSP430FR2433 target I get a panic due to same offset/width for a register. Here's part of the error:

```
thread 'main' panicked at 'conflict in the same module
OLD Register {
    name: "UCB0IE",
    description: "USCI B0 Interrupt Enable Register",
    module: "USCI_B0  I2C Mode",
    offset: 1386,
    width: 2,
    fields: []
}
NEW Register {
    name: "UCB0IE__I2C",
    description: "USCI B0 Interrupt Enable Register",
    module: "USCI_B0  I2C Mode",
    offset: 1386,
    width: 2,
    fields: [
            ... etc ....
```

**Comment by pftbest** [comment]
Hello,

The issue here is a combination of several factors:
1) dslite files like to define the same registers many times over, sometimes it is necessary when one register can operate in different modes, like `USCI_B0_I2C_MODE` and `USCI_B0_SPI_MODE`, but sometimes they redefine the same register just to have an alias like `PAIN` and `P1IN`.
2) svd2rust doesn't like duplicated registers, because it is a safety violation. See https://github.com/japaric/svd2rust/issues/16 . When svd2rust sees a register defined twice, it will abort and generate neither.
3) But there is a loophole in svd2rust that allows us to have the duplicated registers if they are placed in a different peripherals.

The MCUs that i worked with didn't have the duplicated registers in the same peripheral(module) so I didn't handle this case and put a guard there so if somebody will hit it we can decide how to deal with it.

Here is the code: https://github.com/pftbest/msp430_svd/blob/master/src/dslite_parser.rs#L64

And here is your conflicted register: https://github.com/pftbest/msp430_svd/blob/master/msp430-gcc-support-files/targetdb/Modules/msp430/USCI_B0__I2C_Mode_6.xml#L158

As you can see one register doesn't have any fields on it, but the other have many fields. So one solution here could be to keep the register that has fields and discard the empty one.

I will try to fix it today if i will have time, if not then tomorrow. feel free to ping me in IRC if you have more questions.
